/**
 * Vocabulaire de base livré avec BYKO : Agile, Scrum, IT, développement, architecture, design — termes et abréviations
 * courants dans toutes les entreprises, en français et en anglais. Ce fichier est une donnée : l'enrichir, c'est ajouter une ligne.
 *
 * - `term`  : comment on l'écrit / le dit en réunion.
 * - `meaning` : la signification, donnée à l'IA (jamais à la reconnaissance vocale).
 * - `aliases` : façons dont la reconnaissance vocale l'écrit de travers (« dev ops » pour « DevOps »), corrigées vers `term`.
 *   Jamais de traduction ni de forme développée (« pull request » n'est pas un alias de « PR ») et jamais un mot courant
 *   (« us », « front », « solide »…) : un alias remplace tout ce qu'il touche.
 * - `fixCase` : corriger aussi la casse du terme lui-même (« github » → « GitHub »). Réservé aux termes qui ne sont pas des
 *   mots courants : jamais « art », « ci », « po »…
 */

export interface BuiltinEntry {
  term: string
  meaning: string
  aliases?: string[]
  fixCase?: boolean
}

const d = (term: string, meaning: string, aliases?: string[], fixCase = false): BuiltinEntry => ({
  term,
  meaning,
  ...(aliases && aliases.length > 0 ? { aliases } : {}),
  ...(fixCase ? { fixCase } : {}),
})

export const BUILTIN_GLOSSARY: BuiltinEntry[] = [
  // ── Agile, Scrum, Kanban ─────────────────────────────────────────────────────────────────────
  d("Scrum", "cadre agile : équipes auto-organisées, itérations courtes (sprints), rôles et cérémonies définis", ["scram", "scrame"], true),
  d("sprint", "itération de durée fixe (1 à 4 semaines) à l'issue de laquelle on livre un incrément"),
  d("sprint planning", "réunion de début de sprint : l'équipe choisit ce qu'elle s'engage à réaliser"),
  d("daily", "daily Scrum : point quotidien de 15 minutes de l'équipe (aussi « mêlée quotidienne », « stand-up »)"),
  d("stand-up", "point debout quotidien, synonyme de daily", ["stand up", "standup"]),
  d("sprint review", "revue de sprint : démonstration de l'incrément aux parties prenantes"),
  d("rétro", "rétrospective de sprint : l'équipe analyse son fonctionnement et décide des améliorations", ["retro"]),
  d("backlog", "liste priorisée de tout ce qui reste à faire sur le produit", ["back log"]),
  d("product backlog", "backlog du produit, géré par le Product Owner", ["product back log"]),
  d("sprint backlog", "éléments choisis pour le sprint en cours, avec le plan pour les réaliser"),
  d("refinement", "affinage du backlog : préciser, découper et estimer les éléments à venir"),
  d("PO", "Product Owner : responsable de la valeur du produit et de la priorité du backlog"),
  d("Product Owner", "responsable de la valeur du produit et du backlog", ["product owneur"]),
  d("SM", "Scrum Master : garant de la méthode Scrum et facilitateur de l'équipe"),
  d("Scrum Master", "garant de la méthode Scrum, facilite l'équipe et lève les obstacles"),
  d("DoD", "Definition of Done : critères qui rendent un élément réellement terminé"),
  d("DoR", "Definition of Ready : critères pour qu'un élément soit prêt à entrer dans un sprint"),
  d("AC", "Acceptance Criteria : critères d'acceptation d'une user story"),
  d("user story", "besoin exprimé du point de vue de l'utilisateur : « en tant que… je veux… afin de… »"),
  d("epic", "gros ensemble fonctionnel, découpé en plusieurs user stories", ["épic"]),
  d("story points", "unité relative d'estimation de l'effort d'une user story", ["storie points"]),
  d("planning poker", "technique d'estimation collective avec des cartes"),
  d("vélocité", "quantité de travail (en story points) qu'une équipe termine par sprint"),
  d("burndown", "graphique du travail restant au fil du sprint", ["burn down"]),
  d("burnup", "graphique du travail accompli face au périmètre total", ["burn up"]),
  d("Kanban", "méthode de flux : tableau visuel, limitation du travail en cours", ["can ban", "kan ban"], true),
  d("WIP", "Work In Progress : travail en cours (on limite le WIP dans Kanban)", ["w i p"]),
  d("lead time", "délai entre la demande d'un élément et sa livraison"),
  d("cycle time", "durée de traitement d'un élément une fois démarré"),
  d("throughput", "débit : nombre d'éléments terminés par période"),
  d("timebox", "durée fixe et non extensible allouée à une activité", ["time box"]),
  d("spike", "courte exploration technique pour lever une incertitude avant d'estimer"),
  d("MVP", "Minimum Viable Product : version minimale apportant de la valeur et permettant d'apprendre"),
  d("POC", "Proof Of Concept : preuve de faisabilité technique"),
  d("incrément", "version utilisable et potentiellement livrable produite à la fin d'un sprint"),
  d("impediment", "obstacle qui bloque l'équipe (le Scrum Master le lève)", ["impédiment"]),
  d("SAFe", "Scaled Agile Framework : cadre pour appliquer l'agilité à grande échelle", ["sa fe"]),
  d("PI planning", "Program Increment Planning : planification commune de plusieurs équipes sur ~10 semaines (SAFe)"),
  d("ART", "Agile Release Train : groupe d'équipes alignées sur un même objectif (SAFe)"),
  d("RTE", "Release Train Engineer : facilitateur de l'ART (SAFe)"),
  d("LeSS", "Large-Scale Scrum : Scrum appliqué à plusieurs équipes"),
  d("OKR", "Objectives and Key Results : méthode de fixation d'objectifs mesurables", ["o k r"]),
  d("KPI", "Key Performance Indicator : indicateur clé de performance", ["k p i"]),
  d("roadmap", "feuille de route : vision des livrables dans le temps", ["road map"]),
  d("stakeholder", "partie prenante : toute personne impactée ou intéressée par le produit"),
  d("XP", "eXtreme Programming : pratiques d'ingénierie agile (TDD, pair programming, intégration continue…)"),
  d("pair programming", "programmation à deux sur un même poste", ["pair programing"]),
  d("mob programming", "toute l'équipe travaille ensemble sur le même code"),
  d("swarming", "toute l'équipe se concentre sur un même élément pour le finir"),
  d("hotfix", "correctif urgent livré hors du cycle normal", ["hot fix"]),
  d("dette technique", "raccourcis de conception qui coûtent plus cher à maintenir plus tard"),
  d("RACI", "matrice des rôles : Responsable, Approbateur (Accountable), Consulté, Informé"),
  d("Gantt", "diagramme de planification en barres dans le temps"),
  d("cycle en V", "méthode de projet séquentielle : spécifier, concevoir, développer, tester par niveaux"),
  d("waterfall", "méthode en cascade : phases séquentielles sans retour"),

  // ── Qualité, tests, livraison ────────────────────────────────────────────────────────────────
  d("QA", "Quality Assurance : assurance qualité, tests"),
  d("UAT", "User Acceptance Testing : recette utilisateur"),
  d("recette", "phase de validation du produit par le client ou le métier avant mise en production"),
  d("E2E", "tests de bout en bout (end-to-end) du parcours complet", ["e to e"]),
  d("smoke test", "test rapide vérifiant que les fonctions essentielles marchent"),
  d("non-régression", "tests vérifiant qu'une modification n'a rien cassé d'existant", ["non régression"]),
  d("TDD", "Test-Driven Development : écrire le test avant le code"),
  d("BDD", "Behavior-Driven Development : tests décrits en langage métier (Given/When/Then)"),
  d("test unitaire", "test d'une petite unité de code isolée"),
  d("test d'intégration", "test de plusieurs composants ensemble"),
  d("mock", "faux composant simulant une dépendance dans un test"),
  d("flaky test", "test instable qui passe ou échoue sans changement de code", ["test flaky", "flacky test"]),
  d("couverture de tests", "part du code exécutée par les tests"),
  d("bug", "défaut de fonctionnement"),
  d("MEP", "Mise En Production"),
  d("MCO", "Maintien en Condition Opérationnelle : exploitation et maintenance courantes"),
  d("TMA", "Tierce Maintenance Applicative : maintenance d'une application confiée à un prestataire"),
  d("feature flag", "interrupteur activant ou non une fonctionnalité sans redéploiement"),
  d("canary release", "déploiement progressif sur une petite part des utilisateurs"),
  d("blue-green", "déploiement avec deux environnements identiques, bascule instantanée", ["blue green"]),
  d("rollback", "retour à la version précédente après un déploiement raté", ["roll back"]),
  d("staging", "environnement de pré-production identique à la production"),
  d("préprod", "environnement de pré-production", ["pré-prod", "pre prod", "preprod"]),
  d("A/B test", "comparaison de deux versions auprès d'utilisateurs réels", ["ab test", "a b test"]),

  // ── Développement, outils ────────────────────────────────────────────────────────────────────
  d("API", "Application Programming Interface : interface d'échange entre logiciels", ["a p i"], true),
  d("REST", "style d'API web basé sur HTTP et des ressources"),
  d("GraphQL", "langage de requête d'API où le client choisit les champs", ["graph ql", "graphe ql"], true),
  d("gRPC", "protocole d'appel de procédures à distance performant (Google)", ["g rpc"]),
  d("SDK", "Software Development Kit : kit pour développer avec un service"),
  d("CLI", "Command Line Interface : outil en ligne de commande"),
  d("IDE", "Integrated Development Environment : environnement de développement"),
  d("CI/CD", "intégration continue et déploiement continu : automatisation des tests et des livraisons", ["ci cd", "cicd", "c i c d", "ci-cd"]),
  d("pipeline", "chaîne automatisée de build, tests et déploiement"),
  d("PR", "Pull Request : demande de fusion de code relue par l'équipe", ["pool request", "pull requête"]),
  d("MR", "Merge Request : équivalent de la pull request sur GitLab"),
  d("code review", "relecture du code par un pair avant fusion", ["code revue"]),
  d("Git", "système de gestion de versions distribué"),
  d("GitHub", "plateforme d'hébergement de code Git", ["git hub"], true),
  d("GitLab", "plateforme DevOps basée sur Git", ["git lab"], true),
  d("Bitbucket", "plateforme d'hébergement Git d'Atlassian", ["bit bucket"], true),
  d("branche", "ligne de développement parallèle dans Git"),
  d("merge", "fusion de deux branches"),
  d("rebase", "réécriture de l'historique pour rejouer des commits sur une autre base"),
  d("commit", "enregistrement d'un lot de modifications dans Git"),
  d("cherry-pick", "reprendre un commit précis d'une autre branche", ["cherry pick"]),
  d("monorepo", "un seul dépôt de code pour plusieurs projets", ["mono repo"]),
  d("refactoring", "réorganisation du code sans changer son comportement"),
  d("legacy", "ancien code ou système hérité, souvent difficile à faire évoluer"),
  d("linter", "outil qui détecte les erreurs de style et les défauts dans le code"),
  d("frontend", "partie visible de l'application, côté navigateur", ["front-end", "front end"]),
  d("backend", "partie serveur de l'application", ["back-end", "back end"]),
  d("fullstack", "qui travaille à la fois sur le frontend et le backend", ["full stack", "full-stack"]),
  d("DevOps", "culture et pratiques réunissant développement et exploitation", ["dev ops", "dev-ops"], true),
  d("DevSecOps", "DevOps avec la sécurité intégrée dès le début", ["dev sec ops"], true),
  d("SRE", "Site Reliability Engineering : ingénierie de la fiabilité des services"),
  d("IaC", "Infrastructure as Code : infrastructure décrite et gérée par du code"),
  d("Terraform", "outil d'infrastructure as code (HashiCorp)", ["terra form"], true),
  d("Docker", "conteneurs d'application", undefined, true),
  d("Kubernetes", "orchestrateur de conteneurs", ["kubernetès", "cube nettes", "kubernète"], true),
  d("K8s", "abréviation de Kubernetes", ["k 8 s"]),
  d("Helm", "gestionnaire de paquets pour Kubernetes"),
  d("Ansible", "outil d'automatisation de configuration", undefined, true),
  d("AWS", "Amazon Web Services : cloud d'Amazon", ["a w s"]),
  d("GCP", "Google Cloud Platform", ["g c p"]),
  d("Azure", "cloud de Microsoft"),
  d("serverless", "exécution de code sans gérer de serveur", ["server less"]),
  d("lambda", "fonction serverless (AWS Lambda)"),
  d("VPC", "Virtual Private Cloud : réseau privé virtuel dans le cloud"),
  d("CDN", "Content Delivery Network : réseau de distribution de contenu"),
  d("DNS", "Domain Name System : annuaire des noms de domaine"),
  d("TLS", "Transport Layer Security : chiffrement des échanges web"),
  d("SSO", "Single Sign-On : une seule connexion pour plusieurs applications"),
  d("OAuth", "protocole d'autorisation déléguée", ["o auth", "oh auth"], true),
  d("OIDC", "OpenID Connect : couche d'identité au-dessus d'OAuth 2.0"),
  d("SAML", "format d'échange d'authentification entre entreprises"),
  d("JWT", "JSON Web Token : jeton signé d'authentification", ["j w t"], true),
  d("MFA", "authentification multi-facteurs"),
  d("2FA", "authentification à deux facteurs"),
  d("RBAC", "Role-Based Access Control : droits selon le rôle"),
  d("IAM", "Identity and Access Management : gestion des identités et accès"),
  d("CORS", "Cross-Origin Resource Sharing : règles d'accès entre origines web"),
  d("XSS", "Cross-Site Scripting : injection de script dans une page"),
  d("CSRF", "Cross-Site Request Forgery : requête forgée à l'insu de l'utilisateur"),
  d("OWASP", "organisation de référence en sécurité applicative (Top 10)", ["o wasp"], true),
  d("CVE", "Common Vulnerabilities and Exposures : identifiant public de faille"),
  d("SAST", "analyse statique de la sécurité du code"),
  d("DAST", "analyse dynamique de la sécurité de l'application en exécution"),
  d("SBOM", "Software Bill Of Materials : liste des composants d'un logiciel"),
  d("RGPD", "Règlement général sur la protection des données (GDPR)", ["r g p d"]),
  d("CNIL", "autorité française de protection des données"),
  d("SQL", "langage de requête de bases de données relationnelles", ["s q l"]),
  d("NoSQL", "bases de données non relationnelles", ["no sql"], true),
  d("ORM", "Object-Relational Mapping : correspondance objets/tables"),
  d("CRUD", "Create, Read, Update, Delete : opérations de base sur des données"),
  d("ETL", "Extract, Transform, Load : chaîne de traitement de données"),
  d("PostgreSQL", "base de données relationnelle open source", ["post gres"], true),
  d("MySQL", "base de données relationnelle", ["my sql"], true),
  d("MongoDB", "base de données documentaire", ["mongo db"], true),
  d("Redis", "base de données en mémoire, utilisée comme cache", ["redice"], true),
  d("Kafka", "plateforme de streaming d'événements", undefined, true),
  d("RabbitMQ", "gestionnaire de files de messages", ["rabbit mq"], true),
  d("Elasticsearch", "moteur de recherche et d'analyse", ["elastic search"], true),
  d("Prometheus", "outil de supervision et de métriques"),
  d("Grafana", "tableaux de bord de supervision", ["grafanna"], true),
  d("Datadog", "plateforme de supervision", ["data dog"], true),
  d("Sentry", "suivi des erreurs applicatives"),
  d("observabilité", "capacité à comprendre l'état d'un système via logs, métriques et traces"),
  d("SLI", "Service Level Indicator : mesure de la qualité d'un service"),
  d("SLO", "Service Level Objective : objectif de qualité de service"),
  d("SLA", "Service Level Agreement : engagement contractuel de niveau de service"),
  d("MTTR", "Mean Time To Recovery : temps moyen de rétablissement"),
  d("RTO", "Recovery Time Objective : durée maximale d'interruption acceptable"),
  d("RPO", "Recovery Point Objective : perte de données maximale acceptable"),
  d("post-mortem", "analyse d'un incident après coup, sans chercher de coupable", ["postmortem", "post mortem"]),
  d("runbook", "procédure pas à pas pour traiter un incident ou une opération", ["run book"]),
  d("astreinte", "période où une personne est joignable pour traiter les incidents"),
  d("incident", "interruption ou dégradation d'un service"),
  d("Jira", "outil de suivi de tickets d'Atlassian", ["gira", "djira", "jirra"], true),
  d("Confluence", "wiki d'Atlassian", undefined, true),
  d("Trello", "tableaux Kanban", undefined, true),
  d("Figma", "outil de design d'interfaces collaboratif", ["figmat", "fig ma"], true),
  d("Notion", "outil de notes et de documentation"),
  d("Postman", "outil de test d'API", undefined, true),
  d("Swagger", "outils de documentation d'API (OpenAPI)", undefined, true),
  d("OpenAPI", "spécification de description d'API REST", ["open api"], true),
  d("JSON", "format d'échange de données", ["j son"]),
  d("YAML", "format de configuration lisible", ["yamel"], true),
  d("HTML", "langage de structure des pages web"),
  d("CSS", "langage de style des pages web"),
  d("TypeScript", "JavaScript avec typage statique", ["type script"], true),
  d("JavaScript", "langage du web", ["java script"], true),
  d("Node.js", "environnement d'exécution JavaScript côté serveur", ["node js", "nodejs"], true),
  d("React", "bibliothèque d'interfaces JavaScript"),
  d("Vue", "framework d'interfaces JavaScript"),
  d("Angular", "framework d'interfaces de Google"),
  d("Next.js", "framework React avec rendu serveur", ["next js", "nextjs"], true),
  d("npm", "gestionnaire de paquets JavaScript", ["n p m"], true),
  d("SPA", "Single Page Application : application web sur une seule page"),
  d("SSR", "Server-Side Rendering : rendu des pages côté serveur"),
  d("PWA", "Progressive Web App : application web installable"),
  d("SEO", "Search Engine Optimization : référencement naturel"),
  d("i18n", "internationalisation : préparer un logiciel à plusieurs langues", ["i 18 n"]),
  d("l10n", "localisation : adapter un logiciel à une langue et une culture"),
  d("LLM", "Large Language Model : grand modèle de langage", ["l l m"]),
  d("RAG", "Retrieval-Augmented Generation : génération appuyée sur des documents retrouvés"),
  d("prompt", "consigne donnée à une IA générative"),
  d("embedding", "représentation vectorielle d'un texte pour la recherche sémantique"),
  d("fine-tuning", "ré-entraînement d'un modèle sur des données spécifiques", ["fine tuning", "finetuning"]),

  // ── Architecture ─────────────────────────────────────────────────────────────────────────────
  d("microservices", "architecture en petits services indépendants", ["micro services", "micro-services"]),
  d("monolithe", "application construite d'un seul bloc"),
  d("DDD", "Domain-Driven Design : conception pilotée par le domaine métier"),
  d("bounded context", "contexte borné : frontière où un modèle métier a un sens précis"),
  d("architecture hexagonale", "architecture isolant le cœur métier des détails techniques (ports et adaptateurs)"),
  d("clean architecture", "architecture en couches où le métier ne dépend de rien"),
  d("CQRS", "Command Query Responsibility Segregation : séparer lecture et écriture"),
  d("event sourcing", "stocker les événements plutôt que l'état courant", ["event-sourcing"]),
  d("event-driven", "architecture pilotée par les événements", ["event driven"]),
  d("saga", "séquence de transactions distribuées avec compensations"),
  d("API gateway", "point d'entrée unique devant les services", ["api gate way"]),
  d("service mesh", "couche réseau gérant les échanges entre microservices"),
  d("load balancer", "répartiteur de charge entre plusieurs serveurs"),
  d("reverse proxy", "serveur intermédiaire placé devant les services"),
  d("cache", "stockage temporaire pour accélérer les accès"),
  d("idempotence", "propriété d'une opération qu'on peut rejouer sans changer le résultat"),
  d("SOLID", "cinq principes de conception orientée objet"),
  d("DRY", "Don't Repeat Yourself : ne pas dupliquer la connaissance"),
  d("KISS", "Keep It Simple, Stupid : privilégier la simplicité"),
  d("YAGNI", "You Aren't Gonna Need It : ne pas construire ce dont on n'a pas besoin"),
  d("MVC", "Model-View-Controller : séparation modèle, vue, contrôleur"),
  d("MVVM", "Model-View-ViewModel : variante de MVC"),
  d("ADR", "Architecture Decision Record : trace d'une décision d'architecture et de sa raison"),
  d("C4", "modèle de diagrammes d'architecture en quatre niveaux (contexte, conteneurs, composants, code)"),
  d("UML", "Unified Modeling Language : langage de modélisation"),
  d("TOGAF", "cadre d'architecture d'entreprise"),
  d("HLD", "High-Level Design : conception de haut niveau"),
  d("LLD", "Low-Level Design : conception détaillée"),
  d("SPOF", "Single Point Of Failure : point unique de défaillance"),
  d("HA", "High Availability : haute disponibilité"),
  d("scalabilité", "capacité à supporter plus de charge"),
  d("latence", "délai de réponse d'un système"),
  d("SI", "système d'information"),
  d("DSI", "Direction des Systèmes d'Information"),
  d("MOA", "Maîtrise d'ouvrage : le client, qui exprime le besoin"),
  d("MOE", "Maîtrise d'œuvre : l'équipe qui réalise la solution"),
  d("AMOA", "Assistance à Maîtrise d'Ouvrage"),
  d("ESN", "Entreprise de Services du Numérique (ex-SSII)"),

  // ── Design, produit ──────────────────────────────────────────────────────────────────────────
  d("UX", "User Experience : expérience utilisateur"),
  d("UI", "User Interface : interface utilisateur"),
  d("design system", "ensemble cohérent de composants, règles et tokens de design"),
  d("design tokens", "valeurs de design nommées (couleurs, espacements, typographies)"),
  d("wireframe", "maquette schématique d'un écran", ["wire frame"]),
  d("maquette", "représentation visuelle d'un écran"),
  d("prototype", "maquette interactive pour tester un parcours"),
  d("persona", "profil type d'utilisateur utilisé pour concevoir"),
  d("user journey", "parcours utilisateur : étapes vécues pour atteindre un objectif"),
  d("Storybook", "catalogue interactif de composants d'interface", ["story book"], true),
  d("accessibilité", "conception utilisable par tous, y compris les personnes en situation de handicap"),
  d("WCAG", "Web Content Accessibility Guidelines : référentiel international d'accessibilité web", ["w c a g"]),
  d("RGAA", "Référentiel Général d'Amélioration de l'Accessibilité (France)"),
  d("responsive", "interface qui s'adapte à la taille de l'écran"),
  d("dark mode", "thème sombre"),
  d("UX writing", "rédaction des textes d'interface"),
  d("time to market", "délai de mise sur le marché", ["time-to-market"]),
  d("go-to-market", "stratégie de lancement d'un produit", ["go to market"]),
  d("churn", "taux de départ des clients ou utilisateurs"),
  d("NPS", "Net Promoter Score : mesure de la recommandation client"),
  d("MRR", "Monthly Recurring Revenue : revenu récurrent mensuel"),
  d("ARR", "Annual Recurring Revenue : revenu récurrent annuel"),
]
